### ISSUE TITLE
Todos for the next weeks

### ISSUE THREAD

**Issue by ratnanil** [arc2r/book#3]
- [x] Integrate chapters "interactive" and "static" maps
- [x] write Chapters "Aspect and Slope" 
- [x] write Chapters "Focal Statistics" (package `terra`) 
- [x] "Reclassify Raster"
- [x] write chapter "Topology toolset" (use data "Leistungsnachweis" from Module GIS (laup)
- [x] Chapter "Joins and Relates" (Data Management Toolbox): `left_join`, `full_join` ect use the Übungen from Research Methods PrePro 1 & 2
- [x] Surface Toolset
- [x] Zonal Toolset

**Comment by KimboGilda** [comment]
minor additions as well as a "clearer" structure added

**Comment by KimboGilda** [comment]
surface toolset -- basically this is a subtitle for the section that contains tools such as aspect, slope, reclassify etc. This is implemented -- so I consider this point as already completed

**Comment by ratnanil** [comment]
I'm crossing off the last to todo, due to #58
