### ISSUE TITLE
Replace data-files with the arc2r packge

### ISSUE THREAD

**Issue by ratnanil** [arc2r/book#85]
hey Nikos,

This is an effort to merge many issue into one. Can you resolve the following issues by replacing the datafiles with the arc2r package data?

- [ ] #66
- [ ] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [ ] #71
- [ ] #73
- [ ] #74
- [ ] #75
- [ ] #76
- [ ] #77

**Comment by KimboGilda** [comment]
@ratnanil  Nils I understand the scope of this replacement, but on the other hand in the first two chapters we explain how the users can import datasets of any type (raster, vector) and also presenting different ways of performing it (e.g for raster, with raster or terra package). Isn't it a little bit contradictory?

**Comment by ratnanil** [comment]
I was thinking: explain importing in the first chapter, and then only use internal datasets thereafter. Which is why I didnt suggest replacing the datasets in chapters "Data"
